TrackSpot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lf.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),  # Update the login URL pattern

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lf/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('check-username/', views.check_username_availability, name='check_username_availability'),
    path('login/profile/', views.profile, name="profile"),
    path('main/',views.main_page, name="main_page"),
    path('submit_answers/', views.submit_answers, name='submit_answers'),
    path('get_claims_and_responses/<int:item_id>/', views.get_claims_and_responses, name='get_claims_and_responses'),
    path('get_item_details/<int:item_id>/', views.get_item_details, name='get_item_details'),
    path('approve_claim/', views.approve_claim, name='approve_claim'),  # Add this line

]

lf/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
# from django.contrib.auth import get_user_model
from django.conf import settings


class WebsiteUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self.create_user(username, email, password, **extra_fields)

def default_profile_image_path():
    return 'profile_images/default.avif'
class WebsiteUser(AbstractBaseUser, PermissionsMixin):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)
    prn_number = models.CharField(max_length=20, unique=True)
    college_id_image = models.ImageField(upload_to='college_ids/', blank=True, null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    profile_image = models.ImageField(upload_to='profile_images/', default=default_profile_image_path, blank=True, null=True)
    is_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = WebsiteUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

    @property
    def is_anonymous(self):
        return False

    @property
    def is_authenticated(self):
        return True

class UploadedItem(models.Model):
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    description = models.TextField()
    location = models.CharField(max_length=100, null=True)
    # contact = models.CharField(max_length=100)
    image = models.ImageField(upload_to='uploaded_items/', null=True)
    claimed = models.BooleanField(default=False)
    def __str__(self):
        return self.name

class Question(models.Model):
    item = models.ForeignKey('UploadedItem', related_name='questions', on_delete=models.CASCADE)
    text = models.CharField(max_length=255)

    def __str__(self):
        return self.text

class Answer(models.Model):
    item = models.ForeignKey('UploadedItem', related_name='answers', on_delete=models.CASCADE)
    question = models.ForeignKey('Question', related_name='answers', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer_text = models.TextField()

    def __str__(self):
        return f"Answer by {self.user.username} for question '{self.question.text}' on item '{self.item.name}'"



class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    approver_username = models.CharField(max_length=100,default="MYAdmin")  # Add field for approver's username
    approver_phone_number = models.CharField(max_length=15,default="1234567897")  # Add field for approver's phone number
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} - {self.message}"

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- ===============================================-->
  <!--    Document Title-->
  <!-- ===============================================-->
  <title>TrackSpot</title>


  <!-- ===============================================-->
  <!-- Favicons -->
  <!-- =============================================== -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/logo.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/logo.png' %}">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/logo.png' %}">
  <!-- Change the href to your logo.png file -->
  <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
  <meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/mstile-150x150.png' %}">
  <meta name="theme-color" content="#ffffff">

  <!-- Stylesheets -->
  <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />

</head>


<body>

  <!-- ===============================================-->
  <!--    Main Content-->
  <!-- ===============================================-->
  <main class="main" id="top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
      <div class="container"><a class="navbar-brand d-flex align-items-center fw-bold fs-2"
          href="{% url 'index' %}#faq">
          <div class="text-warning">Track</div>
          <div class="text-1000">Spot</div>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto pt-2 pt-lg-0">
            <li class="nav-item"><a class="nav-link fw-medium active" aria-current="page"
                href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link fw-medium" href="{% url 'index' %}#features">Key Features</a></li>
            <li class="nav-item"><a class="nav-link fw-medium" href="{% url 'index' %}#faq">FAQ</a></li>

          </ul>
          <form class="ps-lg-5">
            <a href="{% url 'register' %}">
              <button class="btn btn-lg btn-primary rounded-pill order-0" type="button">register</button>
            </a>
          </form>
        </div>
      </div>
    </nav>


<div class="container1">
    <div class="heading1">Sign In</div>
    <form id="signin-form" class="form1" method="post">
        {% csrf_token %}
        <input required class="input" type="text" name="username" id="username" placeholder="Username">
        <input required class="input" type="password" name="password" id="password" placeholder="Password">
        <input class="login-button" type="submit" value="Sign In">
    </form>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('signin-form').addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent form submission

        var csrfToken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
        var username = document.getElementById('username').value;
        var password = document.getElementById('password').value;

        // Make AJAX request to login endpoint
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/login/', true);
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.setRequestHeader('X-CSRFToken', csrfToken); // Set CSRF token in the header
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                var response = JSON.parse(xhr.responseText);
                if (response.success) {
                    window.location.href = response.redirect_url;
                } else {
                    alert(response.message); // Display message in alert dialogue
                }
            }
        };
        xhr.send('username=' + encodeURIComponent(username) + '&password=' + encodeURIComponent(password));
    });
});
</script>


  </main>
  <!-- ===============================================-->
  <!--    End of Main Content-->
  <!-- ===============================================-->



  <!-- ===============================================-->
  <!--    JavaScripts-->
  <!-- ===============================================-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
  <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendors/is/is.min.js' %}"></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
  <script src="{% static 'assets/js/theme.js' %}"></script>

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400&amp;display=swap"
    rel="stylesheet">
</body>

</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>TrackSpot</title>


    <!-- ===============================================-->
    <!-- Favicons -->
    <!-- =============================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/logo.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/logo.png' %}">
    <!-- Change the href to your logo.png file -->
    <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">

    <!-- Stylesheets -->
    <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />

</head>


<body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
            <div class="container"><a class="navbar-brand d-flex align-items-center fw-bold fs-2"
                    href="{% url 'index' %}">
                    <div class="text-warning">Track</div>
                    <div class="text-1000">Spot</div>
                </a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto pt-2 pt-lg-0">
                        <li class="nav-item" data-anchor="data-anchor">
                            <a class="nav-link fw-medium active" aria-current="page" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item" data-anchor="data-anchor"><a class="nav-link fw-medium"
                                href="#features">Key Features</a></li>
                        <li class="nav-item" data-anchor="data-anchor"><a class="nav-link fw-medium"
                                href="#pricing">Pricing</a></li>
                        <li class="nav-item" data-anchor="data-anchor"><a class="nav-link fw-medium"
                                href="#testimonial">Testimonial</a></li>
                        <li class="nav-item" data-anchor="data-anchor"><a class="nav-link fw-medium" href="#faq">FAQ</a>
                        </li>
                    </ul>
                    <form class="ps-lg-5">
                        <a href="{% url 'login' %}">
                            <button class="btn btn-lg btn-primary rounded-pill order-0" type="button">Login</button>
                        </a>
                    </form>
                </div>
            </div>
        </nav>


        <div class="container1">
            <div class="heading1">Sign Up</div>
            <div id="registration-messages"></div>
            <div id="registration-errors" class="errors"></div>
            <form id="signup-form" class="form1" method="post" action="{% url 'register' %}"
                enctype="multipart/form-data">
                {% csrf_token %}
                <input required class="input" type="text" name="first_name" id="first_name" placeholder="First Name">
                <input class="input" type="text" name="middle_name" id="middle_name" placeholder="Middle Name">
                <input required class="input" type="text" name="last_name" id="last_name" placeholder="Last Name">
                <input required class="input" type="text" name="phone_number" id="phone_number"
                    placeholder="Phone Number">
                <input required class="input" type="email" name="email" id="email" placeholder="E-mail">
                <input required class="input" type="text" name="username" id="username" placeholder="Username">
                <span id="usernameValidation"></span> <!-- Display validation message here -->
                <input required class="input" type="password" name="password1" id="password" placeholder="Password">
                <div id="password-feedback" style="color: red;"></div> <!-- Feedback text -->
                <input required class="input" type="password" name="password2" id="confirm_password"
                    placeholder="Confirm Password">
                <input required class="input" type="text" name="prn_number" id="prn_number" placeholder="PRN Number">
                <input type="file" id="id_image" name="college_id_image" style="display: none;">
                <button type="button" id="upload-button" class="cssbuttons-io-button">
                    <svg viewBox="0 0 640 512" fill="white" height="1em" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M144 480C64.5 480 0 415.5 0 336c0-62.8 40.2-116.2 96.2-135.9c-.1-2.7-.2-5.4-.2-8.1c0-88.4 71.6-160 160-160c59.3 0 111 32.2 138.7 80.2C409.9 102 428.3 96 448 96c53 0 96 43 96 96c0 12.2-2.3 23.8-6.4 34.6C596 238.4 640 290.1 640 352c0 70.7-57.3 128-128 128H144zm79-217c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l39-39V392c0 13.3 10.7 24 24 24s24-10.7 24-24V257.9l39 39c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-80-80c-9.4-9.4-24.6-9.4-33.9 0l-80 80z">
                        </path>
                    </svg>
                    <span>Upload ID</span>
                </button>
                <input class="login-button" type="submit" value="Sign Up">
            </form>

        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                var usernameInput = $('#username');
                var usernameValidation = $('#usernameValidation');
                var submitButton = $('.login-button');

                function updateUsernameValidation(data) {
                    if (data.available) {
                        usernameValidation.html('<span style="color: green;">Username is available!</span>');
                        submitButton.prop('disabled', false);
                    } else {
                        usernameValidation.html('<span style="color: red;">' + data.error + '</span>');
                        submitButton.prop('disabled', true);
                    }
                }

                // Function to handle form submission
                $('#signup-form').on('submit', function (event) {
                    // Prevent default form submission
                    event.preventDefault();

                    // Your form submission handling code goes here
                    var form = $(this);
                    var formData = new FormData(form[0]); // Create FormData object to send form data

                    $.ajax({
                        url: form.attr('action'),
                        method: form.attr('method'),
                        data: formData,
                        contentType: false,
                        processData: false,
                        success: function (response) {
                            if (response.success) {
                                $('#registration-messages').html('<p>' + response.message + '</p>');
                                window.location.href = '/login';
                            } else {
                                var errors = JSON.parse(response.errors);
                                var errorMessage = '';
                                for (var field in errors) {
                                    errorMessage += field + ': ' + errors[field][0].message + '\n'; // Accessing the first error message for each field
                                }
                                alert(errorMessage);
                            }
                        },
                        error: function (xhr, status, error) {
                            console.error(xhr.responseText);
                            alert('An error occurred while processing your request. Please try again.');
                        }
                    });

                });

                // Username input validation
                usernameInput.on('input', function () {
                    var username = $(this).val();
                    if (username.length === 0) {
                        usernameValidation.html('');
                        submitButton.prop('disabled', false);
                        return;
                    }

                    $.ajax({
                        url: '/check-username/',  // Updated URL
                        method: 'POST',
                        data: {
                            'username': username,
                            'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                        },
                        success: function (data) {
                            updateUsernameValidation(data);
                        }
                    });
                });

                // Disable submit button initially
                submitButton.prop('disabled', true);

                // Trigger file input field when upload button is clicked
                $('#upload-button').on('click', function () {
                    $('#id_image').click();
                });
            });
        </script>

        <!-- ===============================================-->
        <!--    JavaScripts-->
        <!-- ===============================================-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/is/is.min.js' %}"></script>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
        <script src="{% static 'assets/js/theme.js' %}"></script>

        <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400&amp;display=swap"
            rel="stylesheet">
</body>

</html>